package borgol.infrastructure.persistence;

import borgol.core.domain.*;
import borgol.infrastructure.config.DatabaseConnection;

import java.sql.*;
import java.util.*;
import java.util.LinkedHashMap;

/**
 * Borgol платформын бүх өгөгдлийн хандалтын нэгдсэн Repository.
 * Хэрэглэгч, Жор, Кафе, Нийгмийн сүлжээний бүх SQL үйлдлийг гүйцэтгэнэ.
 *
 * ═══════════════════════════════════════════════════════
 * Загвар: Repository / DAO (Data Access Object) — GoF
 * ═══════════════════════════════════════════════════════
 * Зорилго: Бизнесийн логик (BorgolService) өгөгдлийн сангийн
 * дэлгэрэнгүйгээс тусгаарлагдана. Service нь зөвхөн домэйн
 * объектуудтай ажиллаж, SQL-ийг огт мэдэхгүй байна.
 *
 * Зарчим (SOLID): Dependency Inversion — Service нь Repository-ийн
 * интерфейсээс хамаарна, тодорхой SQL хэрэгжүүлэлтээс биш.
 */
public class BorgolRepository {

    // DatabaseConnection singleton-г DI (Dependency Injection) аргаар хүлээн авна
    // → тест хийхэд mock connection орлуулах боломжтой болно
    private final DatabaseConnection db;

    public BorgolRepository(DatabaseConnection db) {
        this.db = db;
        initSchema(); // Конструктороос шууд схем үүсгэнэ — startup-д нэг удаа ажиллана
    }

    // ── Схем үүсгэх ──────────────────────────────────────────────────────────
    // Зарчим: Идемпотент (CREATE TABLE IF NOT EXISTS) — хэдэн удаа дуудсан ч
    // нэмэлт хүснэгт үүсэхгүй, аюулгүй.

    private void initSchema() {
        try (Statement s = conn().createStatement()) {
            // ── borgol_users: хэрэглэгчийн үндсэн хүснэгт ──────────────────
            // GENERATED BY DEFAULT AS IDENTITY → PostgreSQL auto-increment ID
            // UNIQUE NOT NULL → давхардсан нэр, и-мэйл хориглоно
            s.execute("""
                CREATE TABLE IF NOT EXISTS borgol_users (
                    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username        VARCHAR(50)  UNIQUE NOT NULL,
                    email           VARCHAR(100) UNIQUE NOT NULL,
                    password_hash   VARCHAR(255) NOT NULL,
                    bio             VARCHAR(500) DEFAULT '',
                    avatar_url      VARCHAR(255) DEFAULT '',
                    expertise_level VARCHAR(20)  DEFAULT 'BEGINNER',
                    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                )""");
            // ── user_flavor_prefs: хэрэглэгч бүрийн амт сонголт ─────────────
            // Composite PRIMARY KEY → нэг хэрэглэгч нэг амтыг давхардуулан нэмж чадахгүй
            // ON DELETE CASCADE → хэрэглэгч устгагдахад амт сонголтууд нь автоматаар устана
            s.execute("""
                CREATE TABLE IF NOT EXISTS user_flavor_prefs (
                    user_id INT,
                    flavor  VARCHAR(30),
                    PRIMARY KEY (user_id, flavor),
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── user_follows: нийгмийн дагах граф ───────────────────────────
            // Нэг хэрэглэгч нөгөөг дагах "many-to-many" харилцаа
            // Composite PK → хоёр дахин дагах боломжгүй
            s.execute("""
                CREATE TABLE IF NOT EXISTS user_follows (
                    follower_id  INT,
                    following_id INT,
                    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (follower_id, following_id),
                    FOREIGN KEY (follower_id)  REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (following_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── recipes: кофе жорын хүснэгт ─────────────────────────────────
            // image_url → migration-д TEXT болгон өргөжүүлнэ (base64 зураг дэмжих)
            s.execute("""
                CREATE TABLE IF NOT EXISTS recipes (
                    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    author_id     INT           NOT NULL,
                    title         VARCHAR(100)  NOT NULL,
                    description   VARCHAR(2000) DEFAULT '',
                    drink_type    VARCHAR(30)   DEFAULT 'COFFEE',
                    ingredients   TEXT          DEFAULT '',
                    instructions  TEXT          DEFAULT '',
                    brew_time     INT           DEFAULT 0,
                    difficulty    VARCHAR(20)   DEFAULT 'MEDIUM',
                    image_url     VARCHAR(255)  DEFAULT '',
                    likes_count   INT           DEFAULT 0,
                    comment_count INT           DEFAULT 0,
                    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (author_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── recipe_flavor_tags: жорын амтын шошго ───────────────────────
            // Жор устгагдахад холбоотой шошгонууд автоматаар устана (CASCADE)
            s.execute("""
                CREATE TABLE IF NOT EXISTS recipe_flavor_tags (
                    recipe_id INT,
                    flavor    VARCHAR(30),
                    PRIMARY KEY (recipe_id, flavor),
                    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
                )""");
            // ── recipe_likes: таалагдсан жорын бүртгэл ──────────────────────
            // Нэг хэрэглэгч нэг жорт нэг удаа л like дарж чадна (Composite PK)
            s.execute("""
                CREATE TABLE IF NOT EXISTS recipe_likes (
                    user_id    INT,
                    recipe_id  INT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id, recipe_id),
                    FOREIGN KEY (user_id)   REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (recipe_id) REFERENCES recipes(id)      ON DELETE CASCADE
                )""");
            // ── recipe_comments: жорын сэтгэгдлүүд ──────────────────────────
            // content TEXT → урт сэтгэгдэл дэмжинэ
            s.execute("""
                CREATE TABLE IF NOT EXISTS recipe_comments (
                    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    recipe_id  INT  NOT NULL,
                    author_id  INT  NOT NULL,
                    content    TEXT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (recipe_id) REFERENCES recipes(id)      ON DELETE CASCADE,
                    FOREIGN KEY (author_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── cafes: кафены жагсаалт ───────────────────────────────────────
            // lat/lng → NULL боломжтой, GPS мэдээлэл алга байх тохиолдолд
            // submitted_by ON DELETE SET NULL → хэрэглэгч устгагдсан ч кафе үлдэнэ
            s.execute("""
                CREATE TABLE IF NOT EXISTS cafes (
                    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name           VARCHAR(100)  NOT NULL,
                    address        VARCHAR(255)  DEFAULT '',
                    district       VARCHAR(100)  DEFAULT '',
                    city           VARCHAR(100)  DEFAULT 'Ulaanbaatar',
                    phone          VARCHAR(50)   DEFAULT '',
                    description    VARCHAR(2000) DEFAULT '',
                    hours          VARCHAR(255)  DEFAULT '',
                    avg_rating     DOUBLE PRECISION DEFAULT 0,
                    rating_count   INT              DEFAULT 0,
                    submitted_by   INT,
                    image_url      VARCHAR(255)  DEFAULT '',
                    lat            DOUBLE PRECISION DEFAULT NULL,
                    lng            DOUBLE PRECISION DEFAULT NULL,
                    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (submitted_by) REFERENCES borgol_users(id) ON DELETE SET NULL
                )""");
            // ── cafe_ratings: кафены үнэлгээ ────────────────────────────────
            // Нэг хэрэглэгч нэг кафед нэг удаа л үнэлгээ өгнө (Composite PK)
            // avg_rating → кафены хүснэгтэд denormalized байна (JOIN хэмнэнэ)
            s.execute("""
                CREATE TABLE IF NOT EXISTS cafe_ratings (
                    user_id    INT,
                    cafe_id    INT,
                    rating     INT  NOT NULL,
                    review     VARCHAR(500) DEFAULT '',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id, cafe_id),
                    FOREIGN KEY (user_id)  REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (cafe_id)  REFERENCES cafes(id)        ON DELETE CASCADE
                )""");
            // ── brew_journal: хувийн дархлалын тэмдэглэл ───────────────────
            // 6 тэнхлэгт radar chart-д зориулсан rating баганууд
            // (aroma, flavor, acidity, body, sweetness, finish)
            s.execute("""
                CREATE TABLE IF NOT EXISTS brew_journal (
                    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id          INT    NOT NULL,
                    coffee_bean      VARCHAR(100)     DEFAULT '',
                    origin           VARCHAR(100)     DEFAULT '',
                    roast_level      VARCHAR(30)      DEFAULT '',
                    brew_method      VARCHAR(50)      DEFAULT '',
                    grind_size       VARCHAR(30)      DEFAULT '',
                    water_temp_c     INT              DEFAULT 0,
                    dose_grams       DOUBLE PRECISION DEFAULT 0,
                    yield_grams      DOUBLE PRECISION DEFAULT 0,
                    brew_time_sec    INT              DEFAULT 0,
                    rating_aroma     INT              DEFAULT 5,
                    rating_flavor    INT              DEFAULT 5,
                    rating_acidity   INT              DEFAULT 5,
                    rating_body      INT              DEFAULT 5,
                    rating_sweetness INT              DEFAULT 5,
                    rating_finish    INT              DEFAULT 5,
                    notes            TEXT             DEFAULT '',
                    created_at       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            s.execute("""
                CREATE TABLE IF NOT EXISTS brew_guides (
                    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    method_name   VARCHAR(50)  NOT NULL,
                    description   VARCHAR(500) DEFAULT '',
                    difficulty    VARCHAR(20)  DEFAULT 'MEDIUM',
                    brew_time_min INT          DEFAULT 5,
                    parameters    TEXT         DEFAULT '',
                    steps         TEXT         DEFAULT '',
                    icon          VARCHAR(10)  DEFAULT '☕',
                    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                )""");
            s.execute("""
                CREATE TABLE IF NOT EXISTS learn_articles (
                    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title         VARCHAR(100) NOT NULL,
                    category      VARCHAR(50)  DEFAULT '',
                    content       TEXT         DEFAULT '',
                    icon          VARCHAR(10)  DEFAULT '📖',
                    read_time_min INT          DEFAULT 3,
                    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                )""");
            s.execute("""
                CREATE TABLE IF NOT EXISTS user_equipment (
                    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id    INT          NOT NULL,
                    category   VARCHAR(30)  DEFAULT 'OTHER',
                    name       VARCHAR(100) NOT NULL,
                    brand      VARCHAR(100) DEFAULT '',
                    notes      TEXT         DEFAULT '',
                    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── saved_recipes: хадгалсан жорын хүснэгт ─────────────────────
            // Bookmarks функц — хэрэглэгч дахин уших жорыг хадгална
            // Composite PK → нэг жорыг давхардуулан хадгалах боломжгүй
            s.execute("""
                CREATE TABLE IF NOT EXISTS saved_recipes (
                    user_id    INT NOT NULL,
                    recipe_id  INT NOT NULL,
                    saved_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id, recipe_id),
                    FOREIGN KEY (user_id)   REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (recipe_id) REFERENCES recipes(id)      ON DELETE CASCADE
                )""");
            // ── notifications: мэдэгдлийн хүснэгт ──────────────────────────
            // type: "like" | "comment" | "follow" — аль төрлийн мэдэгдэл болохыг тэмдэглэнэ
            // is_read: уншигдсан эсэхийг хянана — navbar-д тооллого харуулахад ашиглана
            s.execute("""
                CREATE TABLE IF NOT EXISTS notifications (
                    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id      INT          NOT NULL,
                    type         VARCHAR(30)  NOT NULL,
                    from_user_id INT          DEFAULT 0,
                    content_id   INT          DEFAULT 0,
                    message      VARCHAR(255) NOT NULL,
                    is_read      BOOLEAN      DEFAULT FALSE,
                    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── reports: агуулга мэдээлэх хүснэгт ──────────────────────────
            // Модератор систем: pending → resolved / dismissed амьдралын мөчлөг
            // resolved_by → хэн шийдвэрлэсэн (admin-ийн ID)
            // resolved_at → хэзээ шийдвэрлэсэн (аудит зорилгоор)
            s.execute("""
                CREATE TABLE IF NOT EXISTS reports (
                    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    reporter_id  INT          NOT NULL,
                    content_type VARCHAR(20)  NOT NULL,
                    content_id   INT          NOT NULL,
                    reason       VARCHAR(100) NOT NULL,
                    description  VARCHAR(500) DEFAULT '',
                    status       VARCHAR(20)  DEFAULT 'pending',
                    resolved_by  INT          DEFAULT NULL,
                    resolved_at  TIMESTAMP    DEFAULT NULL,
                    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (reporter_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── blocked_users: блоклосон хэрэглэгчдийн хүснэгт ────────────
            // Аюулгүй байдал: блоклосон хэрэглэгчийн агуулгыг нуух зорилготой
            s.execute("""
                CREATE TABLE IF NOT EXISTS blocked_users (
                    blocker_id INT NOT NULL,
                    blocked_id INT NOT NULL,
                    PRIMARY KEY (blocker_id, blocked_id),
                    FOREIGN KEY (blocker_id) REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (blocked_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── user_hashtags: дагасан хэштэгүүдийн хүснэгт ───────────────
            // Feed шүүлтэнд ашиглана — хэрэглэгч дагасан хэштэгтэй жорууд feed-д гарна
            s.execute("""
                CREATE TABLE IF NOT EXISTS user_hashtags (
                    user_id INT         NOT NULL,
                    tag     VARCHAR(50) NOT NULL,
                    PRIMARY KEY (user_id, tag),
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── Баганын миграциуд (PostgreSQL дээр л ажиллана) ──────────────
            // DO $$ BEGIN...END $$ нь PostgreSQL-н syntax — H2 дэмждэггүй.
            // H2 дээр CREATE TABLE-д TEXT ашигладаг тул migration шаардлагагүй.
            boolean isPostgres = conn().getMetaData().getDatabaseProductName()
                                       .toLowerCase().contains("postgresql");
            if (isPostgres) {
                s.execute("""
                    DO $$ BEGIN
                      ALTER TABLE borgol_users ALTER COLUMN avatar_url TYPE TEXT;
                    EXCEPTION WHEN undefined_table THEN NULL;
                    END $$""");
                s.execute("""
                    DO $$ BEGIN
                      ALTER TABLE borgol_users ALTER COLUMN bio TYPE TEXT;
                    EXCEPTION WHEN undefined_table THEN NULL;
                    END $$""");
                s.execute("""
                    DO $$ BEGIN
                      ALTER TABLE recipes ALTER COLUMN image_url TYPE TEXT;
                    EXCEPTION WHEN undefined_table THEN NULL;
                    END $$""");
                s.execute("""
                    DO $$ BEGIN
                      ALTER TABLE cafes ALTER COLUMN image_url TYPE TEXT;
                    EXCEPTION WHEN undefined_table THEN NULL;
                    END $$""");
            }
            // ── bean_bags: кофены уут бүртгэл ──────────────────────────────
            s.execute("""
                CREATE TABLE IF NOT EXISTS bean_bags (
                    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id         INT          NOT NULL REFERENCES borgol_users(id) ON DELETE CASCADE,
                    name            VARCHAR(120) NOT NULL,
                    roaster         VARCHAR(100) DEFAULT '',
                    origin          VARCHAR(100) DEFAULT '',
                    roast_level     VARCHAR(20)  DEFAULT 'MEDIUM',
                    roast_date      DATE,
                    remaining_grams NUMERIC(7,1) DEFAULT 0,
                    rating          INT          DEFAULT 0,
                    notes           VARCHAR(500) DEFAULT '',
                    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                )""");
            // ── weather_data column migration (idempotent) ───────────────────
            try {
                s.execute("ALTER TABLE brew_journal ADD COLUMN weather_data VARCHAR(300) DEFAULT ''");
            } catch (Exception ignored) { /* column already exists */ }
        } catch (SQLException e) {
            throw new RuntimeException("Schema initialization failed", e);
        }
    }

    // ── Хэрэглэгчийн үйлдлүүд ────────────────────────────────────────────────
    // Загвар: PreparedStatement ашиглах — SQL injection-оос хамгаалах
    // Зарчим: try-with-resources → Connection/Statement автоматаар хаагдана

    public Optional<User> findUserById(int id) {
        // Optional буцаах → null pointer exception-оос аюулгүй, сервист тодорхой алдаа буцаана
        String sql = "SELECT * FROM borgol_users WHERE id = ?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapUser(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    public Optional<User> findUserByEmail(String email) {
        // LOWER() хоёр талд → том/жижиг үсгийг ялгахгүй хайх (case-insensitive)
        String sql = "SELECT * FROM borgol_users WHERE LOWER(email) = LOWER(?)";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, email);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapUser(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    public Optional<User> findUserByUsername(String username) {
        String sql = "SELECT * FROM borgol_users WHERE LOWER(username) = LOWER(?)";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, username);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapUser(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    public User createUser(String username, String email, String passwordHash) {
        String sql = "INSERT INTO borgol_users (username, email, password_hash) VALUES (?, ?, ?)";
        try (PreparedStatement ps = conn().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, username);
            ps.setString(2, email);
            ps.setString(3, passwordHash);
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    return findUserById(keys.getInt(1)).orElseThrow();
                }
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        throw new RuntimeException("User creation failed");
    }

    public void deleteUser(int id) {
        String sql = "DELETE FROM borgol_users WHERE id = ?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public void updateUser(int id, String bio, String avatarUrl, String expertiseLevel) {
        // Only update avatar_url when a non-blank value is provided, to avoid clearing it
        if (avatarUrl != null && !avatarUrl.isBlank()) {
            String sql = "UPDATE borgol_users SET bio=?, avatar_url=?, expertise_level=? WHERE id=?";
            try (PreparedStatement ps = conn().prepareStatement(sql)) {
                ps.setString(1, bio);
                ps.setString(2, avatarUrl);
                ps.setString(3, expertiseLevel);
                ps.setInt(4, id);
                ps.executeUpdate();
            } catch (SQLException e) { throw new RuntimeException(e); }
        } else {
            String sql = "UPDATE borgol_users SET bio=?, expertise_level=? WHERE id=?";
            try (PreparedStatement ps = conn().prepareStatement(sql)) {
                ps.setString(1, bio);
                ps.setString(2, expertiseLevel);
                ps.setInt(3, id);
                ps.executeUpdate();
            } catch (SQLException e) { throw new RuntimeException(e); }
        }
    }

    public List<String> getUserFlavorPrefs(int userId) {
        String sql = "SELECT flavor FROM user_flavor_prefs WHERE user_id = ?";
        List<String> prefs = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) prefs.add(rs.getString("flavor"));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return prefs;
    }

    public void setUserFlavorPrefs(int userId, List<String> flavors) {
        try {
            try (PreparedStatement del = conn().prepareStatement(
                    "DELETE FROM user_flavor_prefs WHERE user_id = ?")) {
                del.setInt(1, userId);
                del.executeUpdate();
            }
            if (flavors != null) {
                try (PreparedStatement ins = conn().prepareStatement(
                        "INSERT INTO user_flavor_prefs (user_id, flavor) VALUES (?, ?)")) {
                    for (String f : flavors) {
                        ins.setInt(1, userId);
                        ins.setString(2, f);
                        ins.addBatch();
                    }
                    ins.executeBatch();
                }
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public int getFollowerCount(int userId) {
        return count("SELECT COUNT(*) FROM user_follows WHERE following_id = ?", userId);
    }

    public int getFollowingCount(int userId) {
        return count("SELECT COUNT(*) FROM user_follows WHERE follower_id = ?", userId);
    }

    public int getUserRecipeCount(int userId) {
        return count("SELECT COUNT(*) FROM recipes WHERE author_id = ?", userId);
    }

    public boolean isFollowing(int followerId, int followingId) {
        String sql = "SELECT COUNT(*) FROM user_follows WHERE follower_id=? AND following_id=?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, followerId);
            ps.setInt(2, followingId);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() && rs.getInt(1) > 0;
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public void followUser(int followerId, int followingId) {
        String sql = "INSERT INTO user_follows (follower_id, following_id) VALUES (?,?) ON CONFLICT (follower_id, following_id) DO NOTHING";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, followerId);
            ps.setInt(2, followingId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public void unfollowUser(int followerId, int followingId) {
        String sql = "DELETE FROM user_follows WHERE follower_id=? AND following_id=?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, followerId);
            ps.setInt(2, followingId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public List<User> searchUsers(String query) {
        String sql = "SELECT * FROM borgol_users WHERE LOWER(username) LIKE ? OR LOWER(bio) LIKE ? LIMIT 20";
        String pattern = "%" + query.toLowerCase() + "%";
        List<User> users = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, pattern);
            ps.setString(2, pattern);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) users.add(mapUser(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return users;
    }

    // ── Recipe operations ─────────────────────────────────────────────────────

    public List<Recipe> findAllRecipes(int currentUserId, String search, String drinkType, String sort) {
        StringBuilder sql = new StringBuilder("""
            SELECT r.*, u.username AS author_username
            FROM recipes r
            JOIN borgol_users u ON r.author_id = u.id
            WHERE 1=1
            """);
        List<Object> params = new ArrayList<>();
        if (search != null && !search.isBlank()) {
            sql.append(" AND (LOWER(r.title) LIKE ? OR LOWER(r.description) LIKE ?)");
            params.add("%" + search.toLowerCase() + "%");
            params.add("%" + search.toLowerCase() + "%");
        }
        if (drinkType != null && !drinkType.isBlank() && !drinkType.equals("ALL")) {
            sql.append(" AND r.drink_type = ?");
            params.add(drinkType);
        }
        sql.append("TRENDING".equals(sort)
            ? " ORDER BY r.likes_count DESC, r.created_at DESC"
            : " ORDER BY r.created_at DESC");
        sql.append(" LIMIT 50");

        List<Recipe> recipes = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql.toString())) {
            for (int i = 0; i < params.size(); i++) ps.setObject(i + 1, params.get(i));
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) recipes.add(mapRecipe(rs, currentUserId));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return recipes;
    }

    public List<Recipe> getFeedRecipes(int userId, int limit) {
        // Recipes from followed users + own recipes, ordered by date
        String sql = """
            SELECT r.*, u.username AS author_username
            FROM recipes r
            JOIN borgol_users u ON r.author_id = u.id
            WHERE r.author_id = ?
               OR r.author_id IN (SELECT following_id FROM user_follows WHERE follower_id = ?)
            ORDER BY r.created_at DESC
            LIMIT ?
            """;
        List<Recipe> recipes = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setInt(2, userId);
            ps.setInt(3, limit);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) recipes.add(mapRecipe(rs, userId));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return recipes;
    }

    public List<Recipe> getUserRecipes(int authorId, int currentUserId) {
        String sql = """
            SELECT r.*, u.username AS author_username
            FROM recipes r
            JOIN borgol_users u ON r.author_id = u.id
            WHERE r.author_id = ?
            ORDER BY r.created_at DESC
            """;
        List<Recipe> recipes = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, authorId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) recipes.add(mapRecipe(rs, currentUserId));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return recipes;
    }

    public Optional<Recipe> findRecipeById(int id, int currentUserId) {
        String sql = """
            SELECT r.*, u.username AS author_username
            FROM recipes r
            JOIN borgol_users u ON r.author_id = u.id
            WHERE r.id = ?
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapRecipe(rs, currentUserId));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    public Recipe createRecipe(Recipe r) {
        String sql = """
            INSERT INTO recipes
              (author_id, title, description, drink_type, ingredients, instructions,
               brew_time, difficulty, image_url)
            VALUES (?,?,?,?,?,?,?,?,?)
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, r.getAuthorId());
            ps.setString(2, r.getTitle());
            ps.setString(3, nvl(r.getDescription()));
            ps.setString(4, nvl(r.getDrinkType(), "COFFEE"));
            ps.setString(5, nvl(r.getIngredients()));
            ps.setString(6, nvl(r.getInstructions()));
            ps.setInt(7, r.getBrewTime());
            ps.setString(8, nvl(r.getDifficulty(), "MEDIUM"));
            ps.setString(9, nvl(r.getImageUrl()));
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    int newId = keys.getInt(1);
                    saveFlavorTags(newId, r.getFlavorTags());
                    return findRecipeById(newId, r.getAuthorId()).orElseThrow();
                }
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        throw new RuntimeException("Recipe creation failed");
    }

    public Recipe updateRecipe(Recipe r) {
        String sql = """
            UPDATE recipes SET title=?, description=?, drink_type=?,
              ingredients=?, instructions=?, brew_time=?, difficulty=?, image_url=?
            WHERE id=? AND author_id=?
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, r.getTitle());
            ps.setString(2, nvl(r.getDescription()));
            ps.setString(3, nvl(r.getDrinkType(), "COFFEE"));
            ps.setString(4, nvl(r.getIngredients()));
            ps.setString(5, nvl(r.getInstructions()));
            ps.setInt(6, r.getBrewTime());
            ps.setString(7, nvl(r.getDifficulty(), "MEDIUM"));
            ps.setString(8, nvl(r.getImageUrl()));
            ps.setInt(9, r.getId());
            ps.setInt(10, r.getAuthorId());
            int updated = ps.executeUpdate();
            if (updated == 0) throw new IllegalArgumentException("Recipe not found or not owner");
            saveFlavorTags(r.getId(), r.getFlavorTags());
        } catch (SQLException e) { throw new RuntimeException(e); }
        return findRecipeById(r.getId(), r.getAuthorId()).orElseThrow();
    }

    public boolean deleteRecipe(int id, int userId) {
        String sql = "DELETE FROM recipes WHERE id=? AND author_id=?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.setInt(2, userId);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public boolean likeRecipe(int userId, int recipeId) {
        String check = "SELECT COUNT(*) FROM recipe_likes WHERE user_id=? AND recipe_id=?";
        try (PreparedStatement ps = conn().prepareStatement(check)) {
            ps.setInt(1, userId);
            ps.setInt(2, recipeId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next() && rs.getInt(1) > 0) return false; // already liked
            }
        } catch (SQLException e) { throw new RuntimeException(e); }

        String ins = "INSERT INTO recipe_likes (user_id, recipe_id) VALUES (?,?)";
        String upd = "UPDATE recipes SET likes_count = likes_count + 1 WHERE id=?";
        try (PreparedStatement ps1 = conn().prepareStatement(ins);
             PreparedStatement ps2 = conn().prepareStatement(upd)) {
            ps1.setInt(1, userId); ps1.setInt(2, recipeId); ps1.executeUpdate();
            ps2.setInt(1, recipeId); ps2.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
        return true;
    }

    public boolean unlikeRecipe(int userId, int recipeId) {
        String del = "DELETE FROM recipe_likes WHERE user_id=? AND recipe_id=?";
        String upd = "UPDATE recipes SET likes_count = GREATEST(0, likes_count - 1) WHERE id=?";
        try (PreparedStatement ps1 = conn().prepareStatement(del);
             PreparedStatement ps2 = conn().prepareStatement(upd)) {
            ps1.setInt(1, userId); ps1.setInt(2, recipeId);
            int deleted = ps1.executeUpdate();
            if (deleted > 0) { ps2.setInt(1, recipeId); ps2.executeUpdate(); }
            return deleted > 0;
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    // ── Comment operations ────────────────────────────────────────────────────

    public List<RecipeComment> findCommentsByRecipeId(int recipeId) {
        String sql = """
            SELECT c.*, u.username AS author_username
            FROM recipe_comments c
            JOIN borgol_users u ON c.author_id = u.id
            WHERE c.recipe_id = ?
            ORDER BY c.created_at ASC
            """;
        List<RecipeComment> comments = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, recipeId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) comments.add(mapComment(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return comments;
    }

    public RecipeComment addComment(int recipeId, int authorId, String content) {
        String ins = "INSERT INTO recipe_comments (recipe_id, author_id, content) VALUES (?,?,?)";
        String upd = "UPDATE recipes SET comment_count = comment_count + 1 WHERE id=?";
        try (PreparedStatement ps = conn().prepareStatement(ins, Statement.RETURN_GENERATED_KEYS);
             PreparedStatement ps2 = conn().prepareStatement(upd)) {
            ps.setInt(1, recipeId);
            ps.setInt(2, authorId);
            ps.setString(3, content);
            ps.executeUpdate();
            ps2.setInt(1, recipeId); ps2.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    int commentId = keys.getInt(1);
                    return findCommentById(commentId);
                }
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        throw new RuntimeException("Comment creation failed");
    }

    private RecipeComment findCommentById(int id) {
        String sql = """
            SELECT c.*, u.username AS author_username
            FROM recipe_comments c
            JOIN borgol_users u ON c.author_id = u.id
            WHERE c.id = ?
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return mapComment(rs);
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        throw new RuntimeException("Comment not found: " + id);
    }

    // ── Cafe operations ───────────────────────────────────────────────────────

    public List<CafeListing> findAllCafes(int currentUserId, String search, String district) {
        StringBuilder sql = new StringBuilder("""
            SELECT c.*,
                   u.username AS submitted_by_username,
                   cr.rating  AS user_rating,
                   cr.review  AS user_review
            FROM cafes c
            LEFT JOIN borgol_users u ON c.submitted_by = u.id
            LEFT JOIN cafe_ratings cr ON cr.cafe_id = c.id AND cr.user_id = ?
            WHERE 1=1
            """);
        List<Object> params = new ArrayList<>();
        params.add(currentUserId);

        if (search != null && !search.isBlank()) {
            sql.append(" AND (LOWER(c.name) LIKE ? OR LOWER(c.description) LIKE ? OR LOWER(c.address) LIKE ?)");
            String p = "%" + search.toLowerCase() + "%";
            params.add(p); params.add(p); params.add(p);
        }
        if (district != null && !district.isBlank() && !district.equals("ALL")) {
            sql.append(" AND LOWER(c.district) LIKE ?");
            params.add("%" + district.toLowerCase() + "%");
        }
        sql.append(" ORDER BY c.avg_rating DESC, c.rating_count DESC");

        List<CafeListing> cafes = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql.toString())) {
            for (int i = 0; i < params.size(); i++) ps.setObject(i + 1, params.get(i));
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) cafes.add(mapCafe(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return cafes;
    }

    public Optional<CafeListing> findCafeById(int id, int currentUserId) {
        String sql = """
            SELECT c.*,
                   u.username AS submitted_by_username,
                   cr.rating  AS user_rating,
                   cr.review  AS user_review
            FROM cafes c
            LEFT JOIN borgol_users u ON c.submitted_by = u.id
            LEFT JOIN cafe_ratings cr ON cr.cafe_id = c.id AND cr.user_id = ?
            WHERE c.id = ?
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, currentUserId);
            ps.setInt(2, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapCafe(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    public CafeListing createCafe(CafeListing c) {
        String sql = """
            INSERT INTO cafes (name, address, district, city, phone, description, hours, image_url, submitted_by, lat, lng)
            VALUES (?,?,?,?,?,?,?,?,?,?,?)
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, c.getName());
            ps.setString(2, nvl(c.getAddress()));
            ps.setString(3, nvl(c.getDistrict()));
            ps.setString(4, nvl(c.getCity(), "Ulaanbaatar"));
            ps.setString(5, nvl(c.getPhone()));
            ps.setString(6, nvl(c.getDescription()));
            ps.setString(7, nvl(c.getHours()));
            ps.setString(8, nvl(c.getImageUrl()));
            if (c.getSubmittedBy() > 0) ps.setInt(9, c.getSubmittedBy());
            else ps.setNull(9, Types.INTEGER);
            if (c.getLat() != null) ps.setDouble(10, c.getLat()); else ps.setNull(10, Types.DOUBLE);
            if (c.getLng() != null) ps.setDouble(11, c.getLng()); else ps.setNull(11, Types.DOUBLE);
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    return findCafeById(keys.getInt(1), c.getSubmittedBy()).orElseThrow();
                }
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        throw new RuntimeException("Cafe creation failed");
    }

    public void updateCafeCoordinates(int cafeId, double lat, double lng) {
        String sql = "UPDATE cafes SET lat = ?, lng = ? WHERE id = ?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setDouble(1, lat);
            ps.setDouble(2, lng);
            ps.setInt(3, cafeId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    /** Returns cafes within a bounding box (lat/lng range). Cafes with no coordinates are excluded. */
    public List<CafeListing> findCafesNearby(int currentUserId,
                                              double minLat, double maxLat,
                                              double minLng, double maxLng) {
        String sql = """
            SELECT c.*,
                   u.username AS submitted_by_username,
                   cr.rating  AS user_rating,
                   cr.review  AS user_review
            FROM cafes c
            LEFT JOIN borgol_users u ON c.submitted_by = u.id
            LEFT JOIN cafe_ratings cr ON cr.cafe_id = c.id AND cr.user_id = ?
            WHERE c.lat IS NOT NULL AND c.lng IS NOT NULL
              AND c.lat BETWEEN ? AND ?
              AND c.lng BETWEEN ? AND ?
            ORDER BY c.avg_rating DESC
            """;
        List<CafeListing> result = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, currentUserId);
            ps.setDouble(2, minLat);
            ps.setDouble(3, maxLat);
            ps.setDouble(4, minLng);
            ps.setDouble(5, maxLng);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) result.add(mapCafe(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return result;
    }

    public boolean rateCafe(int userId, int cafeId, int rating, String review) {
        if (rating < 1 || rating > 5) throw new IllegalArgumentException("Rating must be 1-5");

        String merge = """
            INSERT INTO cafe_ratings (user_id, cafe_id, rating, review)
            VALUES (?,?,?,?)
            ON CONFLICT (user_id, cafe_id) DO UPDATE SET
                rating = EXCLUDED.rating,
                review = EXCLUDED.review
            """;
        try (PreparedStatement ps = conn().prepareStatement(merge)) {
            ps.setInt(1, userId);
            ps.setInt(2, cafeId);
            ps.setInt(3, rating);
            ps.setString(4, nvl(review));
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }

        // Recalculate avg rating
        String recalc = """
            UPDATE cafes SET
                avg_rating   = (SELECT AVG(CAST(rating AS DOUBLE PRECISION)) FROM cafe_ratings WHERE cafe_id = ?),
                rating_count = (SELECT COUNT(*) FROM cafe_ratings WHERE cafe_id = ?)
            WHERE id = ?
            """;
        try (PreparedStatement ps = conn().prepareStatement(recalc)) {
            ps.setInt(1, cafeId); ps.setInt(2, cafeId); ps.setInt(3, cafeId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
        return true;
    }

    // ── Mapping helpers ───────────────────────────────────────────────────────

    private User mapUser(ResultSet rs) throws SQLException {
        User u = new User(
            rs.getInt("id"),
            rs.getString("username"),
            rs.getString("email"),
            rs.getString("password_hash")
        );
        u.setBio(nullToEmpty(rs.getString("bio")));
        u.setAvatarUrl(nullToEmpty(rs.getString("avatar_url")));
        u.setExpertiseLevel(nullToEmpty(rs.getString("expertise_level")));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) u.setCreatedAt(ts.toLocalDateTime().toString());
        return u;
    }

    private Recipe mapRecipe(ResultSet rs, int currentUserId) throws SQLException {
        Recipe r = new Recipe();
        r.setId(rs.getInt("id"));
        r.setAuthorId(rs.getInt("author_id"));
        r.setAuthorUsername(rs.getString("author_username"));
        r.setTitle(rs.getString("title"));
        r.setDescription(nullToEmpty(rs.getString("description")));
        r.setDrinkType(nullToEmpty(rs.getString("drink_type")));
        r.setIngredients(nullToEmpty(rs.getString("ingredients")));
        r.setInstructions(nullToEmpty(rs.getString("instructions")));
        r.setBrewTime(rs.getInt("brew_time"));
        r.setDifficulty(nullToEmpty(rs.getString("difficulty")));
        r.setImageUrl(nullToEmpty(rs.getString("image_url")));
        r.setLikesCount(rs.getInt("likes_count"));
        r.setCommentCount(rs.getInt("comment_count"));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) r.setCreatedAt(ts.toLocalDateTime().toString());

        // Load flavor tags
        r.setFlavorTags(getRecipeFlavorTags(r.getId()));

        // Check if liked by current user
        if (currentUserId > 0) {
            r.setLikedByCurrentUser(isRecipeLikedBy(currentUserId, r.getId()));
            r.setSavedByCurrentUser(isRecipeSaved(currentUserId, r.getId()));
        }
        return r;
    }

    private List<String> getRecipeFlavorTags(int recipeId) {
        String sql = "SELECT flavor FROM recipe_flavor_tags WHERE recipe_id = ?";
        List<String> tags = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, recipeId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) tags.add(rs.getString("flavor"));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return tags;
    }

    private boolean isRecipeLikedBy(int userId, int recipeId) {
        String sql = "SELECT COUNT(*) FROM recipe_likes WHERE user_id=? AND recipe_id=?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId); ps.setInt(2, recipeId);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() && rs.getInt(1) > 0;
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    private void saveFlavorTags(int recipeId, List<String> tags) throws SQLException {
        try (PreparedStatement del = conn().prepareStatement(
                "DELETE FROM recipe_flavor_tags WHERE recipe_id=?")) {
            del.setInt(1, recipeId);
            del.executeUpdate();
        }
        if (tags != null && !tags.isEmpty()) {
            try (PreparedStatement ins = conn().prepareStatement(
                    "INSERT INTO recipe_flavor_tags (recipe_id, flavor) VALUES (?,?)")) {
                for (String t : tags) {
                    ins.setInt(1, recipeId);
                    ins.setString(2, t);
                    ins.addBatch();
                }
                ins.executeBatch();
            }
        }
    }

    private RecipeComment mapComment(ResultSet rs) throws SQLException {
        RecipeComment c = new RecipeComment();
        c.setId(rs.getInt("id"));
        c.setRecipeId(rs.getInt("recipe_id"));
        c.setAuthorId(rs.getInt("author_id"));
        c.setAuthorUsername(rs.getString("author_username"));
        c.setContent(rs.getString("content"));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) c.setCreatedAt(ts.toLocalDateTime().toString());
        return c;
    }

    private CafeListing mapCafe(ResultSet rs) throws SQLException {
        CafeListing c = new CafeListing();
        c.setId(rs.getInt("id"));
        c.setName(rs.getString("name"));
        c.setAddress(nullToEmpty(rs.getString("address")));
        c.setDistrict(nullToEmpty(rs.getString("district")));
        c.setCity(nullToEmpty(rs.getString("city")));
        c.setPhone(nullToEmpty(rs.getString("phone")));
        c.setDescription(nullToEmpty(rs.getString("description")));
        c.setHours(nullToEmpty(rs.getString("hours")));
        c.setAvgRating(rs.getDouble("avg_rating"));
        c.setRatingCount(rs.getInt("rating_count"));
        c.setSubmittedBy(rs.getInt("submitted_by"));
        c.setSubmittedByUsername(nullToEmpty(rs.getString("submitted_by_username")));
        c.setImageUrl(nullToEmpty(rs.getString("image_url")));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) c.setCreatedAt(ts.toLocalDateTime().toString());
        // GPS coordinates (nullable)
        double lat = rs.getDouble("lat"); if (!rs.wasNull()) c.setLat(lat);
        double lng = rs.getDouble("lng"); if (!rs.wasNull()) c.setLng(lng);
        // User's rating
        int userRating = rs.getInt("user_rating");
        if (!rs.wasNull()) {
            c.setCurrentUserRating(userRating);
            c.setCurrentUserReview(nullToEmpty(rs.getString("user_review")));
        }
        return c;
    }

    // ── Extra user/recipe queries ─────────────────────────────────────────────

    public List<User> findAllUsers(int limit) {
        String sql = """
            SELECT * FROM borgol_users
            ORDER BY (SELECT COUNT(*) FROM user_follows WHERE following_id = borgol_users.id) DESC,
                     created_at DESC
            LIMIT ?
            """;
        List<User> users = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, limit);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) users.add(mapUser(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return users;
    }

    public List<Recipe> getLikedRecipes(int userId, int currentUserId) {
        String sql = """
            SELECT r.*, u.username AS author_username
            FROM recipe_likes rl
            JOIN recipes r ON rl.recipe_id = r.id
            JOIN borgol_users u ON r.author_id = u.id
            WHERE rl.user_id = ?
            ORDER BY rl.created_at DESC
            """;
        List<Recipe> recipes = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) recipes.add(mapRecipe(rs, currentUserId));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return recipes;
    }

    public List<User> getFollowingUsers(int userId) {
        String sql = """
            SELECT u.* FROM borgol_users u
            JOIN user_follows f ON f.following_id = u.id
            WHERE f.follower_id = ?
            ORDER BY f.created_at DESC
            """;
        List<User> users = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) users.add(mapUser(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return users;
    }

    public List<User> getFollowerUsers(int userId) {
        String sql = """
            SELECT u.* FROM borgol_users u
            JOIN user_follows f ON f.follower_id = u.id
            WHERE f.following_id = ?
            ORDER BY f.created_at DESC
            """;
        List<User> users = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) users.add(mapUser(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return users;
    }

    // ── Brew Journal operations ───────────────────────────────────────────────

    public List<BrewJournalEntry> getJournalEntries(int userId) {
        String sql = "SELECT * FROM brew_journal WHERE user_id=? ORDER BY created_at DESC";
        List<BrewJournalEntry> list = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) list.add(mapJournal(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    public Optional<BrewJournalEntry> findJournalEntry(int id, int userId) {
        String sql = "SELECT * FROM brew_journal WHERE id=? AND user_id=?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id); ps.setInt(2, userId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapJournal(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    public BrewJournalEntry createJournalEntry(BrewJournalEntry e) {
        String sql = """
            INSERT INTO brew_journal
              (user_id, coffee_bean, origin, roast_level, brew_method, grind_size,
               water_temp_c, dose_grams, yield_grams, brew_time_sec,
               rating_aroma, rating_flavor, rating_acidity, rating_body,
               rating_sweetness, rating_finish, notes)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, e.getUserId());
            ps.setString(2, nvl(e.getCoffeeBean()));
            ps.setString(3, nvl(e.getOrigin()));
            ps.setString(4, nvl(e.getRoastLevel()));
            ps.setString(5, nvl(e.getBrewMethod()));
            ps.setString(6, nvl(e.getGrindSize()));
            ps.setInt(7, e.getWaterTempC());
            ps.setDouble(8, e.getDoseGrams());
            ps.setDouble(9, e.getYieldGrams());
            ps.setInt(10, e.getBrewTimeSec());
            ps.setInt(11, clamp(e.getRatingAroma()));
            ps.setInt(12, clamp(e.getRatingFlavor()));
            ps.setInt(13, clamp(e.getRatingAcidity()));
            ps.setInt(14, clamp(e.getRatingBody()));
            ps.setInt(15, clamp(e.getRatingSweetness()));
            ps.setInt(16, clamp(e.getRatingFinish()));
            ps.setString(17, nvl(e.getNotes()));
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    return findJournalEntry(keys.getInt(1), e.getUserId()).orElseThrow();
                }
            }
        } catch (SQLException ex) { throw new RuntimeException(ex); }
        throw new RuntimeException("Journal entry creation failed");
    }

    public BrewJournalEntry updateJournalEntry(BrewJournalEntry e) {
        String sql = """
            UPDATE brew_journal SET
              coffee_bean=?, origin=?, roast_level=?, brew_method=?, grind_size=?,
              water_temp_c=?, dose_grams=?, yield_grams=?, brew_time_sec=?,
              rating_aroma=?, rating_flavor=?, rating_acidity=?, rating_body=?,
              rating_sweetness=?, rating_finish=?, notes=?
            WHERE id=? AND user_id=?
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, nvl(e.getCoffeeBean()));
            ps.setString(2, nvl(e.getOrigin()));
            ps.setString(3, nvl(e.getRoastLevel()));
            ps.setString(4, nvl(e.getBrewMethod()));
            ps.setString(5, nvl(e.getGrindSize()));
            ps.setInt(6, e.getWaterTempC());
            ps.setDouble(7, e.getDoseGrams());
            ps.setDouble(8, e.getYieldGrams());
            ps.setInt(9, e.getBrewTimeSec());
            ps.setInt(10, clamp(e.getRatingAroma()));
            ps.setInt(11, clamp(e.getRatingFlavor()));
            ps.setInt(12, clamp(e.getRatingAcidity()));
            ps.setInt(13, clamp(e.getRatingBody()));
            ps.setInt(14, clamp(e.getRatingSweetness()));
            ps.setInt(15, clamp(e.getRatingFinish()));
            ps.setString(16, nvl(e.getNotes()));
            ps.setInt(17, e.getId());
            ps.setInt(18, e.getUserId());
            int updated = ps.executeUpdate();
            if (updated == 0) throw new IllegalArgumentException("Entry not found or not authorized");
        } catch (SQLException ex) { throw new RuntimeException(ex); }
        return findJournalEntry(e.getId(), e.getUserId()).orElseThrow();
    }

    public boolean deleteJournalEntry(int id, int userId) {
        String sql = "DELETE FROM brew_journal WHERE id=? AND user_id=?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id); ps.setInt(2, userId);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    // ── Brew Guides operations ────────────────────────────────────────────────

    public List<BrewGuide> findAllBrewGuides() {
        String sql = "SELECT * FROM brew_guides ORDER BY id ASC";
        List<BrewGuide> list = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) list.add(mapBrewGuide(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    public Optional<BrewGuide> findBrewGuideById(int id) {
        String sql = "SELECT * FROM brew_guides WHERE id=?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapBrewGuide(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    // ── Learn Articles operations ─────────────────────────────────────────────

    public List<LearnArticle> findAllLearnArticles() {
        String sql = "SELECT * FROM learn_articles ORDER BY id ASC";
        List<LearnArticle> list = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) list.add(mapLearnArticle(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    public Optional<LearnArticle> findLearnArticleById(int id) {
        String sql = "SELECT * FROM learn_articles WHERE id=?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapLearnArticle(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    // ── Static content seeding ────────────────────────────────────────────────

    public boolean isStaticContentSeeded() {
        return countNoParam("SELECT COUNT(*) FROM brew_guides") > 0;
    }

    public void seedBrewGuide(BrewGuide g) {
        String sql = """
            INSERT INTO brew_guides (method_name, description, difficulty, brew_time_min, parameters, steps, icon)
            VALUES (?,?,?,?,?,?,?)
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, g.getMethodName());
            ps.setString(2, nvl(g.getDescription()));
            ps.setString(3, nvl(g.getDifficulty(), "MEDIUM"));
            ps.setInt(4, g.getBrewTimeMin());
            ps.setString(5, nvl(g.getParameters()));
            ps.setString(6, nvl(g.getSteps()));
            ps.setString(7, nvl(g.getIcon(), "☕"));
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public void seedLearnArticle(LearnArticle a) {
        String sql = """
            INSERT INTO learn_articles (title, category, content, icon, read_time_min)
            VALUES (?,?,?,?,?)
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, a.getTitle());
            ps.setString(2, nvl(a.getCategory()));
            ps.setString(3, nvl(a.getContent()));
            ps.setString(4, nvl(a.getIcon(), "📖"));
            ps.setInt(5, a.getReadTimeMin());
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public boolean isBeanArticlesSeeded() {
        return countNoParam("SELECT COUNT(*) FROM learn_articles WHERE category = 'Beans'") > 0;
    }

    public boolean isCafesSeeded() {
        return countNoParam("SELECT COUNT(*) FROM cafes") > 0;
    }

    public boolean isDrinkArticlesSeeded() {
        return countNoParam("SELECT COUNT(*) FROM learn_articles WHERE category = 'Drinks'") > 0;
    }

    // ── Mapping helpers (new) ─────────────────────────────────────────────────

    private BrewJournalEntry mapJournal(ResultSet rs) throws SQLException {
        BrewJournalEntry e = new BrewJournalEntry();
        e.setId(rs.getInt("id"));
        e.setUserId(rs.getInt("user_id"));
        e.setCoffeeBean(nullToEmpty(rs.getString("coffee_bean")));
        e.setOrigin(nullToEmpty(rs.getString("origin")));
        e.setRoastLevel(nullToEmpty(rs.getString("roast_level")));
        e.setBrewMethod(nullToEmpty(rs.getString("brew_method")));
        e.setGrindSize(nullToEmpty(rs.getString("grind_size")));
        e.setWaterTempC(rs.getInt("water_temp_c"));
        e.setDoseGrams(rs.getDouble("dose_grams"));
        e.setYieldGrams(rs.getDouble("yield_grams"));
        e.setBrewTimeSec(rs.getInt("brew_time_sec"));
        e.setRatingAroma(rs.getInt("rating_aroma"));
        e.setRatingFlavor(rs.getInt("rating_flavor"));
        e.setRatingAcidity(rs.getInt("rating_acidity"));
        e.setRatingBody(rs.getInt("rating_body"));
        e.setRatingSweetness(rs.getInt("rating_sweetness"));
        e.setRatingFinish(rs.getInt("rating_finish"));
        e.setNotes(nullToEmpty(rs.getString("notes")));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) e.setCreatedAt(ts.toLocalDateTime().toString());
        return e;
    }

    private BrewGuide mapBrewGuide(ResultSet rs) throws SQLException {
        BrewGuide g = new BrewGuide();
        g.setId(rs.getInt("id"));
        g.setMethodName(rs.getString("method_name"));
        g.setDescription(nullToEmpty(rs.getString("description")));
        g.setDifficulty(nullToEmpty(rs.getString("difficulty")));
        g.setBrewTimeMin(rs.getInt("brew_time_min"));
        g.setParameters(nullToEmpty(rs.getString("parameters")));
        g.setSteps(nullToEmpty(rs.getString("steps")));
        g.setIcon(nullToEmpty(rs.getString("icon")));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) g.setCreatedAt(ts.toLocalDateTime().toString());
        return g;
    }

    private LearnArticle mapLearnArticle(ResultSet rs) throws SQLException {
        LearnArticle a = new LearnArticle();
        a.setId(rs.getInt("id"));
        a.setTitle(rs.getString("title"));
        a.setCategory(nullToEmpty(rs.getString("category")));
        a.setContent(nullToEmpty(rs.getString("content")));
        a.setIcon(nullToEmpty(rs.getString("icon")));
        a.setReadTimeMin(rs.getInt("read_time_min"));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) a.setCreatedAt(ts.toLocalDateTime().toString());
        return a;
    }

    // ── Utilities ─────────────────────────────────────────────────────────────

    private Connection conn() { return db.getConnection(); }

    private int count(String sql, int param) {
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, param);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getInt(1) : 0;
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    private int countNoParam(String sql) {
        try (Statement s = conn().createStatement();
             ResultSet rs = s.executeQuery(sql)) {
            return rs.next() ? rs.getInt(1) : 0;
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    private static int clamp(int v) { return Math.max(0, Math.min(10, v)); }
    private static String nvl(String s)           { return s != null ? s : ""; }
    private static String nvl(String s, String d) { return (s != null && !s.isBlank()) ? s : d; }
    private static String nullToEmpty(String s)    { return s != null ? s : ""; }

    // ── Equipment ──────────────────────────────────────────────────────────────

    public List<Equipment> getEquipmentByUser(int userId) {
        String sql = "SELECT * FROM user_equipment WHERE user_id = ? ORDER BY created_at DESC";
        List<Equipment> list = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) list.add(mapEquipment(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    public Equipment addEquipment(int userId, String category, String name, String brand, String notes) {
        String sql = "INSERT INTO user_equipment (user_id, category, name, brand, notes) VALUES (?,?,?,?,?)";
        try (PreparedStatement ps = conn().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, userId);
            ps.setString(2, nvl(category, "OTHER"));
            ps.setString(3, name);
            ps.setString(4, nvl(brand));
            ps.setString(5, nvl(notes));
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    int id = keys.getInt(1);
                    return getEquipmentById(id).orElseThrow();
                }
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        throw new RuntimeException("Failed to create equipment");
    }

    public Optional<Equipment> getEquipmentById(int id) {
        String sql = "SELECT * FROM user_equipment WHERE id = ?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapEquipment(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    public void deleteEquipment(int id, int userId) {
        String sql = "DELETE FROM user_equipment WHERE id = ? AND user_id = ?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.setInt(2, userId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    private Equipment mapEquipment(ResultSet rs) throws SQLException {
        Equipment eq = new Equipment();
        eq.setId(rs.getInt("id"));
        eq.setUserId(rs.getInt("user_id"));
        eq.setCategory(nullToEmpty(rs.getString("category")));
        eq.setName(nullToEmpty(rs.getString("name")));
        eq.setBrand(nullToEmpty(rs.getString("brand")));
        eq.setNotes(nullToEmpty(rs.getString("notes")));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) eq.setCreatedAt(ts.toLocalDateTime().toString());
        return eq;
    }

    private int count(String sql, int p1, int p2) {
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, p1);
            ps.setInt(2, p2);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getInt(1) : 0;
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    // ── Saved Recipes ────────────────────────────────────────────────────────

    public void saveRecipe(int userId, int recipeId) {
        String sql = """
            INSERT INTO saved_recipes (user_id, recipe_id)
            VALUES (?, ?)
            ON CONFLICT (user_id, recipe_id) DO NOTHING
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setInt(2, recipeId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public void unsaveRecipe(int userId, int recipeId) {
        String sql = "DELETE FROM saved_recipes WHERE user_id = ? AND recipe_id = ?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setInt(2, recipeId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public boolean isRecipeSaved(int userId, int recipeId) {
        return count("SELECT COUNT(*) FROM saved_recipes WHERE user_id = ? AND recipe_id = ?",
                     userId, recipeId) > 0;
    }

    public List<Recipe> getSavedRecipes(int userId, int currentUserId) {
        String sql = """
            SELECT r.*, u.username AS author_username
            FROM saved_recipes sr
            JOIN recipes r ON r.id = sr.recipe_id
            JOIN borgol_users u ON u.id = r.author_id
            WHERE sr.user_id = ?
            ORDER BY sr.saved_at DESC
            """;
        List<Recipe> result = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) result.add(mapRecipe(rs, currentUserId));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return result;
    }

    // ── Notifications ────────────────────────────────────────────────────────

    public void createNotification(int userId, String type, int fromUserId, int contentId, String message) {
        if (userId == fromUserId) return; // don't notify yourself
        String sql = """
            INSERT INTO notifications (user_id, type, from_user_id, content_id, message)
            VALUES (?, ?, ?, ?, ?)
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setString(2, type);
            ps.setInt(3, fromUserId);
            ps.setInt(4, contentId);
            ps.setString(5, message);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public List<Map<String, Object>> getNotifications(int userId, int limit) {
        String sql = """
            SELECT n.*, u.username AS from_username, u.avatar_url AS from_avatar
            FROM notifications n
            LEFT JOIN borgol_users u ON u.id = n.from_user_id
            WHERE n.user_id = ?
            ORDER BY n.created_at DESC
            LIMIT ?
            """;
        List<Map<String, Object>> result = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setInt(2, limit);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    Map<String, Object> n = new LinkedHashMap<>();
                    n.put("id",          rs.getInt("id"));
                    n.put("type",        rs.getString("type"));
                    n.put("fromUserId",  rs.getInt("from_user_id"));
                    n.put("fromUsername",rs.getString("from_username"));
                    n.put("fromAvatar",  rs.getString("from_avatar"));
                    n.put("contentId",   rs.getInt("content_id"));
                    n.put("message",     rs.getString("message"));
                    n.put("isRead",      rs.getBoolean("is_read"));
                    n.put("createdAt",   rs.getString("created_at"));
                    result.add(n);
                }
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return result;
    }

    public void markNotificationsRead(int userId) {
        String sql = "UPDATE notifications SET is_read = TRUE WHERE user_id = ?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public int getUnreadNotificationCount(int userId) {
        return count("SELECT COUNT(*) FROM notifications WHERE user_id = ? AND is_read = FALSE", userId);
    }

    // ── Reports ──────────────────────────────────────────────────────────────

    public void createReport(int reporterId, String contentType, int contentId, String reason, String description) {
        String sql = """
            INSERT INTO reports (reporter_id, content_type, content_id, reason, description)
            VALUES (?, ?, ?, ?, ?)
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, reporterId);
            ps.setString(2, contentType);
            ps.setInt(3, contentId);
            ps.setString(4, reason);
            ps.setString(5, description != null ? description : "");
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public List<Map<String, Object>> getAllReports(String status) {
        String where = (status != null && !status.equals("all")) ? "WHERE r.status = ?" : "";
        String sql = """
            SELECT r.*, u.username AS reporter_username
            FROM reports r
            LEFT JOIN borgol_users u ON u.id = r.reporter_id
            """ + where + " ORDER BY r.created_at DESC";
        List<Map<String, Object>> result = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            if (!where.isEmpty()) ps.setString(1, status);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    Map<String, Object> row = new LinkedHashMap<>();
                    row.put("id",               rs.getInt("id"));
                    row.put("reporterUsername",  rs.getString("reporter_username"));
                    row.put("contentType",       rs.getString("content_type"));
                    row.put("contentId",         rs.getInt("content_id"));
                    row.put("reason",            rs.getString("reason"));
                    row.put("description",       rs.getString("description"));
                    row.put("status",            rs.getString("status"));
                    row.put("createdAt",         rs.getString("created_at"));
                    result.add(row);
                }
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return result;
    }

    public void resolveReport(int reportId, int resolvedBy, String status) {
        String sql = """
            UPDATE reports SET status = ?, resolved_by = ?, resolved_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """;
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, status);
            ps.setInt(2, resolvedBy);
            ps.setInt(3, reportId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public int getPendingReportCount() {
        return countNoParam("SELECT COUNT(*) FROM reports WHERE status = 'pending'");
    }

    // ── Block users ───────────────────────────────────────────────────────────

    public void blockUser(int blockerId, int blockedId) {
        String sql = "INSERT INTO blocked_users (blocker_id, blocked_id) VALUES (?, ?) ON CONFLICT DO NOTHING";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, blockerId);
            ps.setInt(2, blockedId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
        // Also unfollow both ways
        String unfollow = "DELETE FROM user_follows WHERE (follower_id = ? AND following_id = ?) OR (follower_id = ? AND following_id = ?)";
        try (PreparedStatement ps = conn().prepareStatement(unfollow)) {
            ps.setInt(1, blockerId); ps.setInt(2, blockedId);
            ps.setInt(3, blockedId); ps.setInt(4, blockerId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public void unblockUser(int blockerId, int blockedId) {
        String sql = "DELETE FROM blocked_users WHERE blocker_id = ? AND blocked_id = ?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, blockerId);
            ps.setInt(2, blockedId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public boolean isBlocked(int blockerId, int blockedId) {
        return count("SELECT COUNT(*) FROM blocked_users WHERE blocker_id = ? AND blocked_id = ?",
                     blockerId, blockedId) > 0;
    }

    // ── Hashtag following ─────────────────────────────────────────────────────

    public void followHashtag(int userId, String tag) {
        String sql = "INSERT INTO user_hashtags (user_id, tag) VALUES (?, ?) ON CONFLICT DO NOTHING";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setString(2, tag.toLowerCase());
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public void unfollowHashtag(int userId, String tag) {
        String sql = "DELETE FROM user_hashtags WHERE user_id = ? AND tag = ?";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setString(2, tag.toLowerCase());
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    public List<String> getUserHashtags(int userId) {
        List<String> tags = new ArrayList<>();
        String sql = "SELECT tag FROM user_hashtags WHERE user_id = ? ORDER BY tag";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) tags.add(rs.getString("tag"));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return tags;
    }

    public List<Recipe> getRecipesByHashtag(int currentUserId, String tag) {
        String sql = """
            SELECT r.*, u.username AS author_username
            FROM recipe_flavor_tags rft
            JOIN recipes r ON r.id = rft.recipe_id
            JOIN borgol_users u ON u.id = r.author_id
            WHERE LOWER(rft.flavor) = LOWER(?)
            ORDER BY r.created_at DESC
            """;
        List<Recipe> result = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, tag);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) result.add(mapRecipe(rs, currentUserId));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return result;
    }

    public List<Map<String, Object>> getTrendingHashtags(int limit) {
        String sql = """
            SELECT flavor AS tag, COUNT(*) AS recipe_count
            FROM recipe_flavor_tags
            GROUP BY flavor
            ORDER BY recipe_count DESC
            LIMIT ?
            """;
        List<Map<String, Object>> result = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, limit);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    Map<String, Object> row = new LinkedHashMap<>();
                    row.put("tag", rs.getString("tag"));
                    row.put("recipeCount", rs.getInt("recipe_count"));
                    result.add(row);
                }
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return result;
    }

    // ── Bean Bag operations ───────────────────────────────────────────────────

    public List<borgol.core.domain.BeanBag> getBeanBags(int userId) {
        String sql = "SELECT * FROM bean_bags WHERE user_id=? ORDER BY created_at DESC";
        List<borgol.core.domain.BeanBag> list = new ArrayList<>();
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) list.add(mapBeanBag(rs));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    public borgol.core.domain.BeanBag createBeanBag(borgol.core.domain.BeanBag b) {
        String sql = """
            INSERT INTO bean_bags (user_id, name, roaster, origin, roast_level,
              roast_date, remaining_grams, rating, notes)
            VALUES (?,?,?,?,?,?,?,?,?)""";
        try (PreparedStatement ps = conn().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, b.getUserId());
            ps.setString(2, nvl(b.getName()));
            ps.setString(3, nvl(b.getRoaster()));
            ps.setString(4, nvl(b.getOrigin()));
            ps.setString(5, nvl(b.getRoastLevel()));
            ps.setObject(6, b.getRoastDate() != null && !b.getRoastDate().isBlank()
                ? java.sql.Date.valueOf(b.getRoastDate()) : null);
            ps.setDouble(7, b.getRemainingGrams());
            ps.setInt(8, b.getRating());
            ps.setString(9, nvl(b.getNotes()));
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) b.setId(keys.getInt(1));
            }
        } catch (SQLException e) { throw new RuntimeException(e); }
        return b;
    }

    public borgol.core.domain.BeanBag updateBeanBag(borgol.core.domain.BeanBag b) {
        String sql = """
            UPDATE bean_bags SET name=?, roaster=?, origin=?, roast_level=?,
              roast_date=?, remaining_grams=?, rating=?, notes=?
            WHERE id=? AND user_id=?""";
        try (PreparedStatement ps = conn().prepareStatement(sql)) {
            ps.setString(1, nvl(b.getName()));
            ps.setString(2, nvl(b.getRoaster()));
            ps.setString(3, nvl(b.getOrigin()));
            ps.setString(4, nvl(b.getRoastLevel()));
            ps.setObject(5, b.getRoastDate() != null && !b.getRoastDate().isBlank()
                ? java.sql.Date.valueOf(b.getRoastDate()) : null);
            ps.setDouble(6, b.getRemainingGrams());
            ps.setInt(7, b.getRating());
            ps.setString(8, nvl(b.getNotes()));
            ps.setInt(9, b.getId());
            ps.setInt(10, b.getUserId());
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
        return b;
    }

    public void deleteBeanBag(int id, int userId) {
        try (PreparedStatement ps = conn().prepareStatement(
                "DELETE FROM bean_bags WHERE id=? AND user_id=?")) {
            ps.setInt(1, id); ps.setInt(2, userId);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException(e); }
    }

    private borgol.core.domain.BeanBag mapBeanBag(ResultSet rs) throws SQLException {
        borgol.core.domain.BeanBag b = new borgol.core.domain.BeanBag();
        b.setId(rs.getInt("id"));
        b.setUserId(rs.getInt("user_id"));
        b.setName(nullToEmpty(rs.getString("name")));
        b.setRoaster(nullToEmpty(rs.getString("roaster")));
        b.setOrigin(nullToEmpty(rs.getString("origin")));
        b.setRoastLevel(nullToEmpty(rs.getString("roast_level")));
        java.sql.Date d = rs.getDate("roast_date");
        b.setRoastDate(d != null ? d.toString() : "");
        b.setRemainingGrams(rs.getDouble("remaining_grams"));
        b.setRating(rs.getInt("rating"));
        b.setNotes(nullToEmpty(rs.getString("notes")));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) b.setCreatedAt(ts.toLocalDateTime().toString());
        return b;
    }

    // ── Journal Stats ─────────────────────────────────────────────────────────

    public Map<String, Object> getJournalStats(int userId) {
        Map<String, Object> stats = new LinkedHashMap<>();
        try (Statement s = conn().createStatement()) {
            // Total entries + avg rating
            try (ResultSet rs = s.executeQuery(
                    "SELECT COUNT(*) AS cnt, " +
                    "AVG((rating_aroma+rating_flavor+rating_acidity+rating_body+rating_sweetness+rating_finish)/6.0) AS avg_rating " +
                    "FROM brew_journal WHERE user_id=" + userId)) {
                if (rs.next()) {
                    stats.put("totalEntries", rs.getInt("cnt"));
                    stats.put("avgRating", rs.getDouble("avg_rating"));
                }
            }
            // Brew method counts
            List<Map<String,Object>> methods = new ArrayList<>();
            try (ResultSet rs = s.executeQuery(
                    "SELECT brew_method, COUNT(*) AS cnt FROM brew_journal " +
                    "WHERE user_id=" + userId + " AND brew_method IS NOT NULL AND brew_method<>'' " +
                    "GROUP BY brew_method ORDER BY cnt DESC")) {
                while (rs.next()) {
                    Map<String,Object> row = new LinkedHashMap<>();
                    row.put("method", rs.getString("brew_method"));
                    row.put("count", rs.getInt("cnt"));
                    methods.add(row);
                }
            }
            stats.put("brewMethods", methods);
            // Monthly avg rating (last 12 months) — wrapped for H2 compatibility
            List<Map<String,Object>> monthly = new ArrayList<>();
            try {
                try (ResultSet rs = s.executeQuery(
                        "SELECT TO_CHAR(created_at,'YYYY-MM') AS month, " +
                        "AVG((rating_aroma+rating_flavor+rating_acidity+rating_body+rating_sweetness+rating_finish)/6.0) AS avg_rating, " +
                        "COUNT(*) AS cnt FROM brew_journal WHERE user_id=" + userId +
                        " AND created_at >= NOW() - INTERVAL '12 months' " +
                        "GROUP BY month ORDER BY month")) {
                    while (rs.next()) {
                        Map<String,Object> row = new LinkedHashMap<>();
                        row.put("month", rs.getString("month"));
                        row.put("avgRating", rs.getDouble("avg_rating"));
                        row.put("count", rs.getInt("cnt"));
                        monthly.add(row);
                    }
                }
            } catch (Exception ignored) { /* H2 fallback: skip monthly */ }
            stats.put("monthly", monthly);
        } catch (SQLException e) { throw new RuntimeException(e); }
        return stats;
    }
}
