package borgol.infrastructure.persistence;

import borgol.infrastructure.config.DatabaseConnection;

import java.sql.Statement;

/**
 * Бүх хүснэгтийн бүтцийг нэг газарт үүсгэнэ.
 * Загвар: Single Responsibility — зөвхөн DDL үүрэгтэй.
 * Идемпотент: CREATE TABLE IF NOT EXISTS — хэдэн удаа дуудсан ч аюулгүй.
 */
public class SchemaInitializer {

    private final DatabaseConnection db;

    public SchemaInitializer(DatabaseConnection db) {
        this.db = db;
    }

    public void run() {
        try (Statement s = db.getConnection().createStatement()) {
            // ── borgol_users: хэрэглэгчийн үндсэн хүснэгт ──────────────────
            // GENERATED BY DEFAULT AS IDENTITY → PostgreSQL auto-increment ID
            // UNIQUE NOT NULL → давхардсан нэр, и-мэйл хориглоно
            s.execute("""
                CREATE TABLE IF NOT EXISTS borgol_users (
                    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username        VARCHAR(50)  UNIQUE NOT NULL,
                    email           VARCHAR(100) UNIQUE NOT NULL,
                    password_hash   VARCHAR(255) NOT NULL,
                    bio             VARCHAR(500) DEFAULT '',
                    avatar_url      VARCHAR(255) DEFAULT '',
                    expertise_level VARCHAR(20)  DEFAULT 'BEGINNER',
                    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                )""");
            // ── user_flavor_prefs: хэрэглэгч бүрийн амт сонголт ─────────────
            // Composite PRIMARY KEY → нэг хэрэглэгч нэг амтыг давхардуулан нэмж чадахгүй
            // ON DELETE CASCADE → хэрэглэгч устгагдахад амт сонголтууд нь автоматаар устана
            s.execute("""
                CREATE TABLE IF NOT EXISTS user_flavor_prefs (
                    user_id INT,
                    flavor  VARCHAR(30),
                    PRIMARY KEY (user_id, flavor),
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── user_follows: нийгмийн дагах граф ───────────────────────────
            // Нэг хэрэглэгч нөгөөг дагах "many-to-many" харилцаа
            // Composite PK → хоёр дахин дагах боломжгүй
            s.execute("""
                CREATE TABLE IF NOT EXISTS user_follows (
                    follower_id  INT,
                    following_id INT,
                    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (follower_id, following_id),
                    FOREIGN KEY (follower_id)  REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (following_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── recipes: кофе жорын хүснэгт ─────────────────────────────────
            // image_url → migration-д TEXT болгон өргөжүүлнэ (base64 зураг дэмжих)
            s.execute("""
                CREATE TABLE IF NOT EXISTS recipes (
                    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    author_id     INT           NOT NULL,
                    title         VARCHAR(100)  NOT NULL,
                    description   VARCHAR(2000) DEFAULT '',
                    drink_type    VARCHAR(30)   DEFAULT 'COFFEE',
                    ingredients   TEXT          DEFAULT '',
                    instructions  TEXT          DEFAULT '',
                    brew_time     INT           DEFAULT 0,
                    difficulty    VARCHAR(20)   DEFAULT 'MEDIUM',
                    image_url     VARCHAR(255)  DEFAULT '',
                    likes_count   INT           DEFAULT 0,
                    comment_count INT           DEFAULT 0,
                    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (author_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── recipe_flavor_tags: жорын амтын шошго ───────────────────────
            // Жор устгагдахад холбоотой шошгонууд автоматаар устана (CASCADE)
            s.execute("""
                CREATE TABLE IF NOT EXISTS recipe_flavor_tags (
                    recipe_id INT,
                    flavor    VARCHAR(30),
                    PRIMARY KEY (recipe_id, flavor),
                    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
                )""");
            // ── recipe_likes: таалагдсан жорын бүртгэл ──────────────────────
            // Нэг хэрэглэгч нэг жорт нэг удаа л like дарж чадна (Composite PK)
            s.execute("""
                CREATE TABLE IF NOT EXISTS recipe_likes (
                    user_id    INT,
                    recipe_id  INT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id, recipe_id),
                    FOREIGN KEY (user_id)   REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (recipe_id) REFERENCES recipes(id)      ON DELETE CASCADE
                )""");
            // ── recipe_comments: жорын сэтгэгдлүүд ──────────────────────────
            // content TEXT → урт сэтгэгдэл дэмжинэ
            s.execute("""
                CREATE TABLE IF NOT EXISTS recipe_comments (
                    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    recipe_id  INT  NOT NULL,
                    author_id  INT  NOT NULL,
                    content    TEXT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (recipe_id) REFERENCES recipes(id)      ON DELETE CASCADE,
                    FOREIGN KEY (author_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── cafes: кафены жагсаалт ───────────────────────────────────────
            // lat/lng → NULL боломжтой, GPS мэдээлэл алга байх тохиолдолд
            // submitted_by ON DELETE SET NULL → хэрэглэгч устгагдсан ч кафе үлдэнэ
            s.execute("""
                CREATE TABLE IF NOT EXISTS cafes (
                    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name           VARCHAR(100)  NOT NULL,
                    address        VARCHAR(255)  DEFAULT '',
                    district       VARCHAR(100)  DEFAULT '',
                    city           VARCHAR(100)  DEFAULT 'Ulaanbaatar',
                    phone          VARCHAR(50)   DEFAULT '',
                    description    VARCHAR(2000) DEFAULT '',
                    hours          VARCHAR(255)  DEFAULT '',
                    avg_rating     DOUBLE PRECISION DEFAULT 0,
                    rating_count   INT              DEFAULT 0,
                    submitted_by   INT,
                    image_url      VARCHAR(255)  DEFAULT '',
                    lat            DOUBLE PRECISION DEFAULT NULL,
                    lng            DOUBLE PRECISION DEFAULT NULL,
                    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (submitted_by) REFERENCES borgol_users(id) ON DELETE SET NULL
                )""");
            // ── cafe_ratings: кафены үнэлгээ ────────────────────────────────
            // Нэг хэрэглэгч нэг кафед нэг удаа л үнэлгээ өгнө (Composite PK)
            // avg_rating → кафены хүснэгтэд denormalized байна (JOIN хэмнэнэ)
            s.execute("""
                CREATE TABLE IF NOT EXISTS cafe_ratings (
                    user_id    INT,
                    cafe_id    INT,
                    rating     INT  NOT NULL,
                    review     VARCHAR(500) DEFAULT '',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id, cafe_id),
                    FOREIGN KEY (user_id)  REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (cafe_id)  REFERENCES cafes(id)        ON DELETE CASCADE
                )""");
            // ── brew_journal: хувийн дархлалын тэмдэглэл ───────────────────
            // 6 тэнхлэгт radar chart-д зориулсан rating баганууд
            // (aroma, flavor, acidity, body, sweetness, finish)
            s.execute("""
                CREATE TABLE IF NOT EXISTS brew_journal (
                    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id          INT    NOT NULL,
                    coffee_bean      VARCHAR(100)     DEFAULT '',
                    origin           VARCHAR(100)     DEFAULT '',
                    roast_level      VARCHAR(30)      DEFAULT '',
                    brew_method      VARCHAR(50)      DEFAULT '',
                    grind_size       VARCHAR(30)      DEFAULT '',
                    water_temp_c     INT              DEFAULT 0,
                    dose_grams       DOUBLE PRECISION DEFAULT 0,
                    yield_grams      DOUBLE PRECISION DEFAULT 0,
                    brew_time_sec    INT              DEFAULT 0,
                    rating_aroma     INT              DEFAULT 5,
                    rating_flavor    INT              DEFAULT 5,
                    rating_acidity   INT              DEFAULT 5,
                    rating_body      INT              DEFAULT 5,
                    rating_sweetness INT              DEFAULT 5,
                    rating_finish    INT              DEFAULT 5,
                    notes            TEXT             DEFAULT '',
                    created_at       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            s.execute("""
                CREATE TABLE IF NOT EXISTS brew_guides (
                    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    method_name   VARCHAR(50)  NOT NULL,
                    description   VARCHAR(500) DEFAULT '',
                    difficulty    VARCHAR(20)  DEFAULT 'MEDIUM',
                    brew_time_min INT          DEFAULT 5,
                    parameters    TEXT         DEFAULT '',
                    steps         TEXT         DEFAULT '',
                    icon          VARCHAR(10)  DEFAULT '☕',
                    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                )""");
            s.execute("""
                CREATE TABLE IF NOT EXISTS learn_articles (
                    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title         VARCHAR(100) NOT NULL,
                    category      VARCHAR(50)  DEFAULT '',
                    content       TEXT         DEFAULT '',
                    icon          VARCHAR(10)  DEFAULT '📖',
                    read_time_min INT          DEFAULT 3,
                    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                )""");
            s.execute("""
                CREATE TABLE IF NOT EXISTS user_equipment (
                    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id    INT          NOT NULL,
                    category   VARCHAR(30)  DEFAULT 'OTHER',
                    name       VARCHAR(100) NOT NULL,
                    brand      VARCHAR(100) DEFAULT '',
                    notes      TEXT         DEFAULT '',
                    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── saved_recipes: хадгалсан жорын хүснэгт ─────────────────────
            // Bookmarks функц — хэрэглэгч дахин уших жорыг хадгална
            // Composite PK → нэг жорыг давхардуулан хадгалах боломжгүй
            s.execute("""
                CREATE TABLE IF NOT EXISTS saved_recipes (
                    user_id    INT NOT NULL,
                    recipe_id  INT NOT NULL,
                    saved_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id, recipe_id),
                    FOREIGN KEY (user_id)   REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (recipe_id) REFERENCES recipes(id)      ON DELETE CASCADE
                )""");
            // ── notifications: мэдэгдлийн хүснэгт ──────────────────────────
            // type: "like" | "comment" | "follow" — аль төрлийн мэдэгдэл болохыг тэмдэглэнэ
            // is_read: уншигдсан эсэхийг хянана — navbar-д тооллого харуулахад ашиглана
            s.execute("""
                CREATE TABLE IF NOT EXISTS notifications (
                    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id      INT          NOT NULL,
                    type         VARCHAR(30)  NOT NULL,
                    from_user_id INT          DEFAULT 0,
                    content_id   INT          DEFAULT 0,
                    message      VARCHAR(255) NOT NULL,
                    is_read      BOOLEAN      DEFAULT FALSE,
                    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── reports: агуулга мэдээлэх хүснэгт ──────────────────────────
            // Модератор систем: pending → resolved / dismissed амьдралын мөчлөг
            // resolved_by → хэн шийдвэрлэсэн (admin-ийн ID)
            // resolved_at → хэзээ шийдвэрлэсэн (аудит зорилгоор)
            s.execute("""
                CREATE TABLE IF NOT EXISTS reports (
                    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    reporter_id  INT          NOT NULL,
                    content_type VARCHAR(20)  NOT NULL,
                    content_id   INT          NOT NULL,
                    reason       VARCHAR(100) NOT NULL,
                    description  VARCHAR(500) DEFAULT '',
                    status       VARCHAR(20)  DEFAULT 'pending',
                    resolved_by  INT          DEFAULT NULL,
                    resolved_at  TIMESTAMP    DEFAULT NULL,
                    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (reporter_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── blocked_users: блоклосон хэрэглэгчдийн хүснэгт ────────────
            // Аюулгүй байдал: блоклосон хэрэглэгчийн агуулгыг нуух зорилготой
            s.execute("""
                CREATE TABLE IF NOT EXISTS blocked_users (
                    blocker_id INT NOT NULL,
                    blocked_id INT NOT NULL,
                    PRIMARY KEY (blocker_id, blocked_id),
                    FOREIGN KEY (blocker_id) REFERENCES borgol_users(id) ON DELETE CASCADE,
                    FOREIGN KEY (blocked_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── user_hashtags: дагасан хэштэгүүдийн хүснэгт ───────────────
            // Feed шүүлтэнд ашиглана — хэрэглэгч дагасан хэштэгтэй жорууд feed-д гарна
            s.execute("""
                CREATE TABLE IF NOT EXISTS user_hashtags (
                    user_id INT         NOT NULL,
                    tag     VARCHAR(50) NOT NULL,
                    PRIMARY KEY (user_id, tag),
                    FOREIGN KEY (user_id) REFERENCES borgol_users(id) ON DELETE CASCADE
                )""");
            // ── Баганын миграциуд (PostgreSQL дээр л ажиллана) ──────────────
            // DO $$ BEGIN...END $$ нь PostgreSQL-н syntax — H2 дэмждэггүй.
            // H2 дээр CREATE TABLE-д TEXT ашигладаг тул migration шаардлагагүй.
            boolean isPostgres = db.getConnection().getMetaData().getDatabaseProductName()
                                   .toLowerCase().contains("postgresql");
            if (isPostgres) {
                s.execute("""
                    DO $$ BEGIN
                      ALTER TABLE borgol_users ALTER COLUMN avatar_url TYPE TEXT;
                    EXCEPTION WHEN undefined_table THEN NULL;
                    END $$""");
                s.execute("""
                    DO $$ BEGIN
                      ALTER TABLE borgol_users ALTER COLUMN bio TYPE TEXT;
                    EXCEPTION WHEN undefined_table THEN NULL;
                    END $$""");
                s.execute("""
                    DO $$ BEGIN
                      ALTER TABLE recipes ALTER COLUMN image_url TYPE TEXT;
                    EXCEPTION WHEN undefined_table THEN NULL;
                    END $$""");
                s.execute("""
                    DO $$ BEGIN
                      ALTER TABLE cafes ALTER COLUMN image_url TYPE TEXT;
                    EXCEPTION WHEN undefined_table THEN NULL;
                    END $$""");
            }
            // ── bean_bags: кофены уут бүртгэл ──────────────────────────────
            s.execute("""
                CREATE TABLE IF NOT EXISTS bean_bags (
                    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id         INT          NOT NULL REFERENCES borgol_users(id) ON DELETE CASCADE,
                    name            VARCHAR(120) NOT NULL,
                    roaster         VARCHAR(100) DEFAULT '',
                    origin          VARCHAR(100) DEFAULT '',
                    roast_level     VARCHAR(20)  DEFAULT 'MEDIUM',
                    roast_date      DATE,
                    remaining_grams NUMERIC(7,1) DEFAULT 0,
                    rating          INT          DEFAULT 0,
                    notes           VARCHAR(500) DEFAULT '',
                    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                )""");
            // ── weather_data column migration (idempotent) ───────────────────
            try {
                s.execute("ALTER TABLE brew_journal ADD COLUMN weather_data VARCHAR(300) DEFAULT ''");
            } catch (Exception ignored) { /* column already exists */ }

            // ── cafe_checkins ─────────────────────────────────────────────────
            s.execute("""
                CREATE TABLE IF NOT EXISTS cafe_checkins (
                    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cafe_id    INT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
                    user_id    INT NOT NULL REFERENCES borgol_users(id) ON DELETE CASCADE,
                    note       VARCHAR(200) DEFAULT '',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )""");

            // ── user_achievements ─────────────────────────────────────────────
            s.execute("""
                CREATE TABLE IF NOT EXISTS user_achievements (
                    user_id   INT         NOT NULL REFERENCES borgol_users(id) ON DELETE CASCADE,
                    badge_id  VARCHAR(30) NOT NULL,
                    earned_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id, badge_id)
                )""");

            // ── recipe_collections ────────────────────────────────────────────
            s.execute("""
                CREATE TABLE IF NOT EXISTS recipe_collections (
                    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id     INT          NOT NULL REFERENCES borgol_users(id) ON DELETE CASCADE,
                    name        VARCHAR(100) NOT NULL,
                    description VARCHAR(500) DEFAULT '',
                    is_public   BOOLEAN      DEFAULT TRUE,
                    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                )""");
            s.execute("""
                CREATE TABLE IF NOT EXISTS collection_recipes (
                    collection_id INT NOT NULL REFERENCES recipe_collections(id) ON DELETE CASCADE,
                    recipe_id     INT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
                    added_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (collection_id, recipe_id)
                )""");

        } catch (Exception e) {
            throw new RuntimeException("Schema init failed", e);
        }
    }
}
